version: '3.8'

services:
  backend:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      POSTGRES_DB: Courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aarsha@prem49
    ports:
    - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fullstack-network

  springboot:
    image: 'openjdk:11-jre-slim'  # Replace with your Spring Boot image if built
    container_name: springboot-api
    build:
      context: ./Youtube_RESTAPI/Youtube_RESTAPI  # path to your backend code
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/Courses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aarsha@prem49
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - backend
    networks:
      - fullstack-network
    ports:
      - "8080:8096"

  frontend:
    build:
      context: ./React-project-effigo/React_App/react_project  # path to your frontend code
    container_name: react-app
    networks:
      - fullstack-network
    ports:
      - "3000:3000"

networks:
  fullstack-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
